name: SCL-metal

on:
    push:
        # trigger on self repo commit

    workflow_dispatch:
        # trigger via REST API (when SCL repo commit)
        inputs:
            sclref:
                description: SCL reference to check out
                required: true
                default: 'default'
                # for some reason, it does not work with a default value;
                # w/o it, the variable is never set.

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    env:
        TARGETS: qemu-sifive_e_rv64 qemu-sifive_e_rv32

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: false

      - name: Check how events works
        run:  echo "SCL-ref is ${{ github.event.inputs.sclref }}";
              echo "GH refs ${GITHUB_SHA}, ${GITHUB_REF}"

      - name: Checkout SCL and Unity submodules
        run: git submodule update --init

      - name: Change SCL branch # event-initiated request
        run: if [ -n "${{ github.event.inputs.sclref }}" ]; then
             (cd scl-metal && git checkout ${{ github.event.inputs.sclref }} )
             else true; fi

      - name: Checkout SCL and Unity submodules
        run:  git submodule status; false

      - name: Fetch all Docker images
        run: docker/bin/dock.sh build /bin/true &&
             docker/bin/dock.sh utest /bin/true

      - name: Build all targets
        run:  docker/bin/dock.sh build scripts/buildall.sh -q -s $TARGETS

      - name: Test all targets
        run: docker/bin/dock.sh utest scripts/utestall.sh build
