name: Build and test SCL-metal

on: [push]

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    env:
        TARGETS: qemu-sifive_e_rv64 qemu-sifive_e_rv32

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true

      - name: Checkout the proper submodule versions
        run: git submodule update --recursive &&
               git submodule status

      - name: Fetch all Docker images
        run: docker/bin/dock.sh build /bin/true &&
             docker/bin/dock.sh utest /bin/true

      - name: Build targets
        run: docker/bin/dock.sh build scripts/buildall.sh -s $TARGETS

      - name: Test targets
        run: docker/bin/dock.sh utest scripts/utestall.sh -q /usr/local/qemu-fdt/bin build
