name: Build RISC-V softmmu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Checkout the proper submodule commits
      run: git submodule update --recursive
    - name: Load Docker toolchain containers
      run: docker/bin/dock.sh /bin/true
    - name: Build project from Docker container
      run: docker/bin/dock.sh scripts/build.sh qemu-sifive_e_rv64
