name: Build RISC-V softmmu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
        matrix:
            dts: [qemu-sifive_e_rv64]
            build: [debug]
        fail-fast: false
        max-parallel: 1

    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Checkout the proper submodule versions
        run: git submodule update --recursive &&
               git submodule status
      - name: Fetch all Docker images
        run: docker/bin/dock.sh build /bin/true &&
             docker/bin/dock.sh utest /bin/true
      - name: Build target ${{ matrix.dts }} ${{ matrix.build }}
        run: docker/bin/dock.sh build scripts/build.sh
                  ${{ matrix.dts }} ${{ matrix.build }}
      - name: Test target ${{ matrix.dts }} ${{ matrix.build }}
        run: docker/bin/dock.sh utest scripts/utest.sh
                  -d bsp/${{ matrix.dts }}/dts/qemu.dts
                  -q /usr/local/qemu-fdt/bin
                  build/${{ matrix.dts }}/${{ matrix.build }}


                #- name: Build RV64, Release mode
    #  run: docker/bin/dock.sh scripts/build.sh
    #            qemu-sifive_e_rv64 RELEASE
    #- name: Static analysis (RV64)
    #  run: docker/bin/dock.sh scripts/build.sh
    #            qemu-sifive_e_rv64 STATIC_ANALYSIS
    #- name: Build RV32, Debug mode
    #  run: docker/bin/dock.sh scripts/build.sh
    #            qemu-sifive_e_rv32 DEBUG
    #- name: Build RV32, Release mode
    #  run: docker/bin/dock.sh scripts/build.sh
    #            qemu-sifive_e_rv32 RELEASE
    #- name: Static analysis (RV32)
    #  run: docker/bin/dock.sh scripts/build.sh
    #            qemu-sifive_e_rv32 STATIC_ANALYSIS
