name: Build RISC-V softmmu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Load Docker toolchain containers
      run: docker/bin/dock.sh /bin/true
    - name: Checkout submodules
      run: git submodule init &&
           git submodule update
    - name: Build project from Docker container
      run: docker/bin/dock.sh scripts/build.sh qemu-sifive_e_rv64
