name: Build RISC-V softmmu

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Load Docker toolchain containers
      run: docker/bin/dock.sh /bin/true
    - name: Clone scl-metal submodule
      uses: actions/checkout@v2
      with:
        repository: sifive/scl-metal
        path: scl
        ref: v2
    - name: Clone test-scl-metal submodule
      uses: actions/checkout@v2
      with:
        repository: sifive/test-scl-metal
        path: tests/scl-metal
        ref: v2
        ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
        persist-credentials: false
    - name: Build project from Docker container
      run: docker/bin/dock.sh scripts/build.sh qemu-sifive_e_rv64
